services:
    mysql:
        container_name: sakila
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: sakila
            MYSQL_ROOT_PASSWORD: G3skbkFH6y
        volumes:
            - ./docker:/var/lib/mysql
            - ./sql:/tmp